name: ASCII Work Shell Script

on: push

jobs:
    ascii_job_3:
        runs-on: ubuntu-latest
        steps:
            - name : checkout repo
              uses: actions/checkout@v4

            - name: List repo Files
              run: ls -ltra