name: Multiple Job Workflow

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name : checkout repo
              uses: actions/checkout@v4

            - name: Install cowsay program
              run: sudo apt-get install cowsay -y
              
            - name: Execute Cowsay command
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
            
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt

    test_job_2:
        needs: ascii_job
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file
            
            - name: Test File exists
              run: grep -i "dragon" dragon.txt
            
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file

            - name: Read File
              run: cat dragon.txt           
                
            - name: Deploy
              run: echo Deploying.....